language: node_js
node_js:
  - '4.4'

# Because installing atom-package-manager is not working on travis, just using
# the install script to install just the test dependencies
install:
  - npm install ava
  - npm install colorable
  - npm install eslint
  - npm install eslint-plugin-github
  - npm install babel-eslint
